[package]
name = "aether"
description = "Experimental Operating System in Rust."
version = "0.0.1"
edition = "2024"
license = "GPL-2.0"
readme = "README"
repository = "https://github.com/ouzuka-m/aether"
keywords = ["no-std", "rust", "memory", "kernel", "embedded"]
categories = ["os", "no-std", "memory-management", "filesystem", "embedded"]

[dependencies]
limine = "0.6"
x86_64 = { version = "0.15", default-features = false, features = ["instructions", "abi_x86_interrupt"] }
spin = { version = "0.12", default-features = false, features = ["spin_mutex", "once", "lazylock"] }
uart_16550 = "0.6"
pc-keyboard = "0.9"
noto-sans-mono-bitmap = { version = "0.3", default-features = false, features = ["size_20", "regular", "unicode-basic-latin"] }
buddy_system_allocator = { version = "0.13", default-features = false, features = ["use_spin"] }
acpi = "6.1"
raw-cpuid = "11.6"

[[bin]]
name = "aether"
test = false
bench = false

[profile.dev]
incremental = true
panic = "abort"

[profile.release]
panic = "abort"
